lobby:
  spawn:
    ==: org.bukkit.Location
    world: world
    x: -320.5
    y: 70.0
    z: 416.5
    pitch: 0.0
    yaw: 90.0
  games:
    bingo:
      name: Bingo
      color: §5
      position:
        ==: org.bukkit.Location
        world: world
        x: -360.5
        y: 69.0
        z: 407.5
        pitch: 0.0
        yaw: 90.0
      material: CRAFTING_TABLE
      slot: 11
    survival:
      name: Survival
      color: §2
      position:
        ==: org.bukkit.Location
        world: world
        x: -360.0
        y: 68.0
        z: 390.5
        pitch: 0.0
        yaw: 180.0
      material: GRASS_BLOCK
      slot: 15
    ttt:
      name: TTT
      color: §4
      position:
        ==: org.bukkit.Location
        world: world
        x: -367.5
        y: 69.0
        z: 416.5
        pitch: 0.0
        yaw: 0.0
      material: IRON_SWORD
      slot: 22
    skywars:
      name: SkyWars
      color: §6
      position:
        ==: org.bukkit.Location
        world: world
        x: -357.5
        y: 63.0
        z: 419.5
        pitch: 0.0
        yaw: 180.0
      material: SNOWBALL
      slot: 29
    gungame:
      name: GunGame
      color: §3
      position:
        ==: org.bukkit.Location
        world: world
        x: -357.5
        y: 74.0
        z: 419.5
        pitch: 0.0
        yaw: 180.0
      material: WOODEN_SWORD
      slot: 33